name: Sterling Pipeline

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Sterling Retail Core
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Execute Cypress Test
        uses: cypress-io/github-action@v6
        